### ISSUE TITLE
normalise year attribute 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/data-quality#1]
On the client side we run into problems when trying to implement filters and sorting on the medadata level.
Especially for the year field (that contains not only years, but dates and time ranges), there is no harmonised format and sorting is not possible. 
Could we get a normalised version of the date (only year would be sufficient for the sorting in the search result list and also for the timeline in the vis dashboard)

![screen shot 2015-09-16 at 11 43 54](https://cloud.githubusercontent.com/assets/4638470/9901483/4dab333c-5c68-11e5-8510-12a48ac5d019.png)

**Comment by jr-dig-orgel** [comment]
This will be solved in the Partner-recommender. 
The new issue: https://github.com/EEXCESS/recommender/issues/21
